### ISSUE TITLE
Wake from deep sleep accelerometer

### ISSUE THREAD

**Issue by benagricola** [dmiddlecamp/fancy-asset-tracker#1] opened 2016-03-07 13:03 UTC
I've been playing with the motion-tracker example for a couple of days and it seems to work great until it goes into deep sleep the second time (e.g. if I wake it up with motion, and then it times out and goes back into deep sleep).

After the second time of going into deep sleep (even if this is only a couple of minutes), it then won't wake up from deep sleep from the accelerometer input.

I haven't yet tried to reduce the deep sleep interval to see if it wakes up based on timer but was wondering if this is something you've seen during development?

Great example though - I'm planning on augmenting this with CellLocate data if a GPS fix can't be acquired.

**Comment by dmiddlecamp** [comment] 2016-06-24 20:10
potential wake-from-deep-sleep fix here?  https://github.com/rickkas7/LIS3DH/blob/master/firmware/examples/1accelwakeasset.cpp

**Comment by benagricola** [comment] 2016-07-18 23:46
So... this actually seems to work pretty well, as long as the accelerometer is reset after waking up, and potentially after movement at all. I've not had any issue with it waking up due to movement so far. Have noticed that the device will detect motion permanently if the electron is not completely flat, which can be a little tricky.

Also noticed that my electron no longer comes back on from deep sleep on an interval any more but that may be down to newer firmware or something, haven't had a chance to investigate.

**Comment by dmiddlecamp** [comment] 2016-07-19 15:21
Hi @benagricola ,

  Thanks for testing that accel reset code, good to know!

Thanks,
David

**Comment by toddmedema** [comment] 2017-01-04 00:48
Following up here, also running into issues where my Electron won't wake from sleep a second time. Here's my code - https://github.com/toddmedema/ebike-tracker

Any ideas what's going on?

**Comment by dmiddlecamp** [comment] 2017-01-04 17:07
I compared this to another project where I use the same accelerometer interrupt / wakeup scheme that hasn't had any wakeup problems.  The key difference seems to be the time the WKP pin is held high after the shock was detected.  I modified the app to use 100ms up, instead of 20ms UP, which I suspect will fix the issue.

New code here:
https://github.com/dmiddlecamp/fancy-asset-tracker/blob/master/motion-tracker/main.ino#L20

Can you give this a try and let me know if this fixes the issue for you?

Thanks,
David

**Comment by toddmedema** [comment] 2017-01-04 18:40
David,

Thank you for getting back so quickly!

Set to 100, it'll wake up from two sleeps instead of one.

Also tried setting it to 125 (same result), 150 and 200 (which both continuously detected motion)

Then tried pulling and running the fancy-asset-tracker code without any modifications... same result. Woke up from two sleeps. Any other ideas? Or is it possible it's a hardware issue / I should contact Particle?

Thank you,

Todd

**Comment by dmiddlecamp** [comment] 2017-01-04 19:11
Hmm, any chance you're running older system firmware?  Can you try updating to the latest system firmware?

**Comment by toddmedema** [comment] 2017-01-04 20:01
Looks like I'm currently running 0.6.0, which is the latest version the firmware manager offers me. What firmware version are you running?

**Comment by toddmedema** [comment] 2017-01-05 03:13
Note: confirmed that the device was able to reliably wake up from the sleep timer many times without issue.

However, after it'd woken up a few times, it no longer properly sensed motion (aka blinked the LED). So, seems like it might be related to not properly calibrating / shutting down / resetting the accelerometer?

**Comment by dmiddlecamp** [comment] 2017-01-05 17:38
Hmm...  The only other major difference between this codebase and other demos where I haven't had the issue, is that I keep the GPS sensor off.  I wonder if it's possible that as a result of the wiring of the asset-tracker-shield, if powering on the GPS interferes with the setup of the accelerometer?  

Could you try not powering up the GPS, or powering up the GPS before the accel, or adding a delay, etc?

**Comment by toddmedema** [comment] 2017-01-06 15:27
Tried commenting out all GPS initialization / checking / publishing code: SUCCESS!
Tried initing GPS before Accelerometer (also adding a delay at the end of `initAccel` for good measure): SUCCESS!

Good call @dmiddlecamp :) Think we can close this. If you're interested, updated [my code](https://github.com/toddmedema/ebike-tracker) with a few handy sleight-of-hands:

- if the device wakes and battery is < 20%, goes back to sleep
- when going to sleep, publish the battery state instead of publishing a fixed sleep string + separate battery state, to help conserve battery + data
- added an ultralight node server to log the events as they happen, since that's the other important part of a tracking system :)

**Comment by dmiddlecamp** [comment] 2017-01-07 18:24
nice!  I'll incorporate the changes when I get a chance and then close the ticket.  :)

**Comment by dmiddlecamp** [comment] 2017-01-12 18:48
attempted to address this here: https://github.com/dmiddlecamp/fancy-asset-tracker/commit/e5713969854bd99c4db9f446eed1c57f2e5bf9ed

**Closed as completed** 2017-01-12 18:47 UTC
